### ISSUE TITLE
Define "infrastructure" titles for Keptn LTS documentation

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1466]
Need consensus on:

* Directory name for the source files.  Oleg's suggestion is lts-1.0.x
* Title on the landing page -- in parallel to 0.19.x, 0.18.x, etc
* Release identifier to be used in URLs, now and in the future.
   * @aepfli thinks he can get "latest" to work for initial release
   * If we do that, what will the URL for this version be when "latest" is lts-2.0.x or something?

Need consensus from @aepfli , @oleg-nenashev , @mowies , and @thisthat

**Comment by mowies** [comment]
I would vote for `1.0.x` folder name and `Release 1.0.x LTS` for the landing page title.
Then the identifier in URLs would still be consistent with older versions and would just be `1.0.x` like the folder name.
I don't really see a reason why we should start using latest now when we don't use it anywhere else in Keptn. It will only make things weird with the following versions.

**Comment by StackScribe** [comment]
I think the justification for implementing "latest" is because we plan to use that approach when we go to the new doc engine and have true version control implemented.  But I defer to you, @oleg-nenashev , and @aepfli here.

**Comment by aepfli** [comment]
i would still call the version by its name, and I would only leave the latest version in the recent directory. if I create a new folder for a new version, or copy the existing `latest` and rename it, to the now "old version" is just a technicality - but it has a big impact.

- we can easily create canonical URLs - because latest is always the up-to-date version
- we still have redirects for the current version, as long as we define aliases, as they will be used to generate pages for those aliases

Alternatively we might just introduce an alias with `latest` but I am not sure, who well redirects for canonical URLs are interpreted by Search engines.

**Comment by StackScribe** [comment]
We did as @mowies suggested above.
