### ISSUE TITLE
Determine whether and how to implement "latest" for LTS docs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1470]
The Keptn LTS docs will initially be published with Hugo, which does not have full version control capabilities like we expect to have with the new doc engine.  Is it possible for us to implement "latest" and, if so, what is the best approach?

@aepfli is working this issue.

https://github.com/keptn/keptn.github.io/pull/1451

**Comment by aepfli** [comment]
Proposal:

- use latest for the most recent version, but always provide an alias with the full version string.
  - this way the version will be found and we do have a normal forwarding too
  - additionally we can setup a canonical URLs for all old pages forwarding to just latest -> backlinking to most recent versions, helps for SEO
- creating a new version would look like following:
   1. copy paste latest folder
   2. rename copy pasted folder to version
   3. change alias in latest to the new version
   4. (maybe remove the old alias in the old version)

Alternations:

- instead of creating the latest version, we could do an alias to the latest on the current version. We would need to regularly change this alias within our process:
  1. Copy paste current version
  2. Rename copy pasted folder to new version
  3. adapt netlify rule
  
   The problem might be, that seo does not like this redirect, and overall how to best handle the redirect - as we would need to create some kind of netlify redirect rule, and also adapt this most likely all the time. I think adapting redirect rules regularly poses a greater risk of an error rather than the normal approach.

**Comment by StackScribe** [comment]
We were not really able to do this for the 1.0 release.   At the end, we had to use the former structure, although this means that the 0.x.x version of Concepts and Installation show at the root level and the 1.0.x version is under the 1.0.x section.  Hopefully we can come up with a better solution and do a silent roll of the docs page.

**Comment by DavidPHirsch** [comment]
close as not planned
