### ISSUE TITLE
Root-level information for outdated versions

### ISSUE THREAD

**Issue by aepfli** [keptn/keptn.github.io#1592]
# Problem

With version `1.0.x`, we moved information regarding the concepts, etc., within the version directory, which makes sense as they evolve with a version. For older versions, newer concepts, etc., might not apply. To avoid cross-references, we left the old parts on the root level. This isn't very clear for people exploring the documentation based on our statistics. Most people are also drawn to the root-level pages rather than the version-specific ones.

![image (6)](https://user-images.githubusercontent.com/9987394/217505573-5de10108-6f78-4329-88da-c0b48e0772be.png)

# Goal

- Ideally, the following sections would be only version specific:
    - concepts
    - installation
    - explore
    - integrations

- current links to the root level pages would redirect to the version within 1.0.x

Soon version 0.18.x and 0.19.x will also be removed from the sidebar, but the documentation will still be present.

# Solution

As soon as 0.18.x and 0.19.x will be hidden from the sidebar. We do have two options:

1. we remove the root level sections and create a redirect to version 1.0.x
2. we move the documentation for version 1.0.x to the root level

## Solution 1

The sidebar won't be as clear anymore, as users will have to select a version before actually having content (it could be handled with some redirect to the current version).

Also, we need to check the CLI golang doc for existing links, which might now be broken.

## Solution 2

It will need more adaptation regarding canonical URL logic. But overall will be a more concise picture.
![image](https://user-images.githubusercontent.com/9987394/217755283-e0a98a44-44cd-48a0-97c1-ad6e136061ac.png)

## extra mile

As we will get some cross-reference issues, most likely even with the hidden documentation, we can copy-paste the root level section into the outdated and still rendered versions - to have no cross-reference issue and still provide a complete picture documentation-wise.

## Additional adaptions

Be careful with the canonical URL logic and adapt accordingly for chosen solutions. 
- for solution number 1, there is most likely nothing that needs to be done
- for solution number 2, there is a little adjustment regarding checking for existing pages, etc.

## Cross-references

Cross-references might be a big topic, but we will have to deal with all of those for each version anyways. In the end, it will end up being a string-replace throughout some documentation folders.

**Comment by StackScribe** [comment]
The "Integrations" section should not be part of this discussion.  The Integrations section shows all Integrations that are available for all/any Keptn releases.  The documentation for each integration identifies which Keptn versions are supported, often with different versions of the Integration supported for different Keptn releases.  So that is handled and we don't need to worry about it.

**Comment by StackScribe** [comment]
All of these suggestions involve changing the fundamental structure of the docs for the earlier releases.  They require a fair amount of work and require some careful reviewing and testing of all the old doc sets -- it is non-trivial work.  The old structure was very problematic -- we did not preserve the version of Concepts or Explore Keptn (which was Quickstart in earlier releases) for the different releases.  We had this crazy arrangement where we updated those root sections for the newest release and, if one was using an earlier release, one got that updated content.

**Comment by StackScribe** [comment]
And yes, I have some non-complementary terms for people who want to continue using a 0.y.z release rather than moving to the LTS release but people are people...  For instance, we know we have users who freeze at I think 0.15.x because they don't want to have to use the upstream git repo for their projects.  We don't want to invest much in supporting these users but why antagonizing them by just breaking something that is working for them now?

**Comment by thisthat** [comment]
I would not put effort into supporting old pre-production releases. Our commitment should be to version 1.x.y which is the LTS and stable version of Keptn. We should prioritize solutions that make the documentation for 1.x.y more accessible and easier to use.

**Comment by StackScribe** [comment]
The more I think about it, the more I am convinced that we should make a copy of the keptn.github.io repo, remove all 1.* content, and build it as "Keptn 0.y.z Documentation" that can have its own link or tab or whatever.  It will basically be what we had for 0.19.x -- we can discuss how far back we go with releases displayed in the sidebar.  Then we remove all the 0.y.z content from the keptn.github.io repo so that is only for V1 and later releases (if any).

**Comment by thisthat** [comment]
After some thought, I suggest going with Solution 2. 
Keptn has reached the LTS status, which means explore, concepts, and installation will NOT change in the future. Hence, we should move these files from the release folder into the root. 
For the problem of dealing with previous version documentation, I would suggest tackling this issue in a follow-up.

**Comment by aepfli** [comment]
Solution 2: looks like with adapted icons (that was just a short copy paste and running the checks, to see if the build still works)
![image](https://user-images.githubusercontent.com/9987394/217747204-2ad4d006-d091-4e38-885a-660b2b09e559.png)
