### ISSUE TITLE
Enhance docs for mac users

### ISSUE THREAD

**Issue by SuperAayush** [keptn/keptn.github.io#1595]
As discussed in the community meeting today the docs can either be made more beginner-friendly by covering the "Create or bring a Kubernetes cluster" section in the installation of keptn for different operating systems separately. 

Being a mac user I faced issues setting up OpenShift and k3s(requiring more storage than my system has). 

My suggestion:
For the time being, [Create or bring a Kubernetes cluster](https://keptn.sh/docs/install/k8s/) can contain a table having a different OS and process that is working fine in that OS until we have a solid doc to provide installation for the system that does not use arch x64. For Example - k3d works fine with mac m1(without doing any changes in memory or CPU requirements)

cc- @DavidPHirsch @agardnerIT @bradmccoydev

**Comment by StackScribe** [comment]
I have assigned this to you, @SuperAayush .  Why don't you create a PR with what you know.  I'm not sure if I agree that it belongs in "Create or bring a Kubernetes cluster" since this is not really related to k8s per se.  You might want to look at what is in https://keptn.sh/docs/1.0.x/install/troubleshooting/ ,  which has some other information about installation issues related to specific platforms, etc.  That is written more as small targeted tidbits, which are easier to provide than a comprehensive table about each O/S and option.  And it already includes some other info related to OpenShift and resources.
