### ISSUE TITLE
Documentation for onboard_service missing for 0.8.x

### ISSUE THREAD

**Issue by laneli** [keptn/keptn.github.io#793]
https://keptn.sh/docs/0.8.x/reference/cli/commands/keptn_onboard_service/

Documentation is not found and returns 404.

**Comment by anthu** [comment]
I ran into this issue due to a reference in https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-08/index.html?index=..%2F..index#12

And as `onboard` is deprecated no documentation will be generated for that command.
See:
https://github.com/keptn/keptn/blob/1937f8461f960b5ba7d6de38ae463fdda9d8769e/cli/cmd/onboard.go#L12

**Comment by johannes-b** [comment]
**Action item**
- Merge the content of the section [Onboard a service](https://keptn.sh/docs/0.9.x/manage/service/#onboard-a-service) into the section [Create a service](https://keptn.sh/docs/0.9.x/manage/service/#create-a-service) 
- Make sure that no `keptn onboard service` command is in the docs


**Definition of Done**

- [ ] Content of [Onboard a service](https://keptn.sh/docs/0.9.x/manage/service/#onboard-a-service) about the Helm Chart requirements are merged into `Create a service`
